alter table bank_accounts add primary key (id);


ALTER TABLE BANK_ACCOUNTS ADD PRIMARY KEY (ID);
ALTER TABLE BANK_TRANSFERS ADD PRIMARY KEY (TXN_ID);
ALTER TABLE BANK_TRANSFERS MODIFY SRC_ACCT_ID REFERENCES BANK_ACCOUNTS (ID);
ALTER TABLE BANK_TRANSFERS MODIFY DST_ACCT_ID REFERENCES BANK_ACCOUNTS (ID);


select * from USER_CONS_COLUMNS where table_name in ('BANK_ACCOUNTS', 'BANK_TRANSFERS');
