#!/usr/bin/env bash
GRAPH_NAME=$1
GRAPH_DIR=$2
if [ -z ${GRAPH_DIR} ]; then
    echo "Postprocessing graph_data/${GRAPH_NAME}_preprocessed.edgelist";
    sed -i -E 's#\\([^\"])#\\\\\1#g' ../../../data/graph_data/${GRAPH_NAME}_preprocessed.edgelist;

    echo "Postprocessing graph_data/${GRAPH_NAME}_redirects.edgelist";
    sed -i -E 's#\\([^\"])#\\\\\1#g' ../../../data/graph_data/${GRAPH_NAME}_redirects.edgelist;
else
    echo "Postprocessing ${GRAPH_DIR}/${GRAPH_NAME}_preprocessed.edgelist";
    sed -i -E 's#\\([^\"])#\\\\\1#g' ../../../${GRAPH_DIR}/${GRAPH_NAME}_preprocessed.edgelist;

    echo "Postprocessing ${GRAPH_DIR}/${GRAPH_NAME}_redirects.edgelist";
    sed -i -E 's#\\([^\"])#\\\\\1#g' ../../../${GRAPH_DIR}/${GRAPH_NAME}_redirects.edgelist;
fi
