DROP TABLE BANK_TRANSFERS;
DROP TABLE BANK_ACCOUNTS;

-- create BANK ACCOUNTS table
CREATE TABLE BANK_ACCOUNTS (
    ID              NUMBER,
    NAME            VARCHAR(400),
    BALANCE         NUMBER(20,2)
);

-- create BANK_TRANSFERS table
CREATE TABLE BANK_TRANSFERS (
    TXN_ID          NUMBER,
    SRC_ACCT_ID     NUMBER,
    DST_ACCT_ID     NUMBER,
    DESCRIPTION     VARCHAR(400),
    AMOUNT          NUMBER
);

ALTER TABLE BANK_ACCOUNTS ADD PRIMARY KEY (ID);
ALTER TABLE BANK_TRANSFERS ADD PRIMARY KEY (TXN_ID);
ALTER TABLE BANK_TRANSFERS MODIFY SRC_ACCT_ID REFERENCES BANK_ACCOUNTS (ID);
ALTER TABLE BANK_TRANSFERS MODIFY DST_ACCT_ID REFERENCES BANK_ACCOUNTS (ID);

-- At this point, you should load the BANK_ACCOUNTS.csv and BANK_TRANSFERS.csv files into the BANK_ACCOUNTS and BANK_TRANSACTIONS tables respectively
